create table if not exists public.events (
  id text primary key,
  title text not null,
  emoji text not null default '🌟',
  date timestamptz not null,
  location text not null,
  capacity integer not null check (capacity > 0),
  description text not null,
  financial_concepts text[] not null default '{}',
  published boolean not null default true,
  photos text[] not null default '{}',
  reflection text not null default '',
  highlights text not null default '',
  waitlist_enabled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.events(id) on delete cascade,
  student_name text not null,
  age integer not null check (age between 8 and 18),
  parent_name text not null,
  parent_email text not null,
  parent_phone text not null default '',
  consent boolean not null default false,
  status text not null default 'confirmed' check (status in ('confirmed', 'waitlist', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.site_analytics (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text not null,
  referrer text,
  created_at timestamptz not null default now()
);

create table if not exists public.site_reload_signals (
  id bigint generated by default as identity primary key,
  requested_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_profiles (
  username text primary key,
  username_hash text not null,
  password_hash text not null,
  salt text not null,
  role text not null default 'viewer' check (role in ('owner', 'manager', 'viewer')),
  created_at timestamptz not null default now()
);

insert into public.admin_profiles (username, username_hash, password_hash, salt, role)
values (
  'admin',
  'afa41df6f5d063848fa0b03ffbaa3c515ca9432deba0996bcaa0795a5edfff0d',
  '24cfd694725ea1b0e62df1b70aef274c05f63053ac7a10f5a74dbeca893e561e',
  'moneymind-owner-admin-salt-v1',
  'owner'
)
on conflict (username) do update set
  username_hash = excluded.username_hash,
  password_hash = excluded.password_hash,
  salt = excluded.salt,
  role = 'owner';

alter table public.events add column if not exists waitlist_enabled boolean not null default false;

alter table public.events enable row level security;
alter table public.registrations enable row level security;
alter table public.site_analytics enable row level security;
alter table public.site_reload_signals enable row level security;
alter table public.admin_profiles enable row level security;

drop policy if exists "Public can read events" on public.events;
create policy "Public can read events"
  on public.events for select
  to anon, authenticated
  using (true);

drop policy if exists "Site can manage events" on public.events;
create policy "Site can manage events"
  on public.events for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Public can read registrations" on public.registrations;
create policy "Public can read registrations"
  on public.registrations for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can create registrations" on public.registrations;
create policy "Public can create registrations"
  on public.registrations for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Site can update registrations" on public.registrations;
create policy "Site can update registrations"
  on public.registrations for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Site can delete registrations" on public.registrations;
create policy "Site can delete registrations"
  on public.registrations for delete
  to anon, authenticated
  using (true);

drop policy if exists "Public can record analytics" on public.site_analytics;
create policy "Public can record analytics"
  on public.site_analytics for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Site can read analytics" on public.site_analytics;
create policy "Site can read analytics"
  on public.site_analytics for select
  to anon, authenticated
  using (true);

drop policy if exists "Site can publish reload signals" on public.site_reload_signals;
create policy "Site can publish reload signals"
  on public.site_reload_signals for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public can read reload signals" on public.site_reload_signals;
create policy "Public can read reload signals"
  on public.site_reload_signals for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can read admin profiles" on public.admin_profiles;
create policy "Admins can read admin profiles"
  on public.admin_profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins can create admin profiles" on public.admin_profiles;
create policy "Admins can create admin profiles"
  on public.admin_profiles for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can delete admin profiles" on public.admin_profiles;
create policy "Admins can delete admin profiles"
  on public.admin_profiles for delete
  to anon, authenticated
  using (true);
